choco install -y vcredist2005
choco install -y vcredist2008
choco install -y vcredist2010
choco install -y vcredist2012
choco install -y vcredist2013
choco install -y vcredist2015
choco install -y googlechrome
choco install -y dotnet3.5
choco install -y dotnet4.5.2
choco install -y dotnet4.6.1
choco install -y 7zip.commandline
choco install -y curl
choco install -y git
choco install -y python2
choco install -y python3
choco install -y sysinternals
choco install -y wget
choco install -y windows-sdk-8.1
choco install -y windows-sdk-10.1
choco install -y visualstudio2012professional
choco install -y cmake
